@APISuite
Feature: [CLOUD API Experimental Suite] - [JVCLD-27456]

  Background:
    Given We are running E2E JVCLD-27456
    And ADMIN logged into the system

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:24:46 GMT
  Scenario: API - Precondition - Create event in community with start date as last day of month - [25293617]
    When Logged in user requests to create open event EVENTFOO with description "testing open event" in community
    Then Event EVENTFOO is created successfully

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:24:11 GMT
  Scenario: API - Verify on event creation screen event duration is maintained when only start date is changed - [25293616]
    When Update Event EVENTFOO EndDate
    Then Event EVENTFOO StartDate Not Changed

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:49:43 GMT
  Scenario: API - Precondition - Create event in Group with start date as last day of month - [25293619]
    When Logged in user requests to create open event EVENTFOO with description "testing open event" in group
    Then Event EVENTFOO is created successfully

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:49:41 GMT
  Scenario: API - Edit event in Community and Verify event duration is maintained when only start date is changed - [25293618]
    When Update Event EVENTFOO EndDate
    Then Event EVENTFOO StartDate Not Changed

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:51:37 GMT
  Scenario: API - Precondition - Create event in Group Project with start date as last day of month - [25293622]
    When Logged in user requests to create event in project under group
      | eventTag | eventDescription |
      | EVENTFOO | my awesome event |
    Then Event EVENTFOO is created successfully

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:51:36 GMT
  Scenario: API - Edit event in Group and Verify event duration is maintained when only start date is changed - [25293621]
    When Update Event EVENTFOO EndDate
    Then Event EVENTFOO StartDate Not Changed

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:52:16 GMT
  Scenario: API - Precondition - Create event in Space with start date as last day of month - [25293624]
    When Logged in user requests to create event under space
      | eventTag | eventDescription |
      | EVENTFOO | my awesome event |
    Then Event EVENTFOO is created successfully

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:52:16 GMT
  Scenario: API - Edit event in Group Project and Verify event duration is maintained when only start date is changed - [25293623]
    When Update Event EVENTFOO EndDate
    Then Event EVENTFOO StartDate Not Changed

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:52:52 GMT
  Scenario: API - Precondition - Create event in Space Project with start date as last day of month - [25293626]
    When Logged in user requests to create event in project under space
      | eventTag | eventDescription |
      | EVENTFOO | my awesome event |
    Then Event EVENTFOO is created successfully

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:52:54 GMT
  Scenario: API - 	Edit event in Space and Verify event duration is maintained when only start date is changed - [25293625]
    When Update Event EVENTFOO EndDate
    Then Event EVENTFOO StartDate Not Changed

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:53:46 GMT
  Scenario: API - Precondition - Create event in Subspace with start date as last day of month - [25311965]
    When Logged in user requests to create event under sub-space
      | eventTag | eventDescription |
      | EVENTFOO | my awesome event |
    Then Event EVENTFOO is created successfully

   # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:53:45 GMT
  Scenario: API - Edit event in Space Project and Verify event duration is maintained when only start date is changed - [25311964]
    When Update Event EVENTFOO EndDate
    Then Event EVENTFOO StartDate Not Changed

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:54:23 GMT
  Scenario: API - Precondition - Create event in Subspace project with start date as last day of month - [25311967]
    When Logged in user requests to create event under sub-space
      | eventTag  | eventDescription |
      | EVENTFSUB | my awesome event |
    Then Event EVENTFSUB is created successfully

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:54:25 GMT
  Scenario: API - Edit event in Subspace and Verify event duration is maintained when only start date is changed - [25311966]
    When Update Event EVENTFSUB EndDate
    Then Event EVENTFSUB StartDate Not Changed

    # Auto generated by chrome-extension on Mon, 22 Apr 2019 16:54:48 GMT
  Scenario: API - Edit event in Subspace project and Verify event duration is maintained when only start date is changed - [25311969]
    When Update Event EVENTFOO EndDate
    Then Event EVENTFOO StartDate Not Changed
    