@APISuite
Feature: [CLOUD API Experimental Suite] - [JVCLD-26981]

  Background:
    Given We are running E2E JVCLD-26981
    And ADMIN logged into the system
    And User BZU is created

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 08:23:40 GMT
  Scenario: API - User likes Discussion created by another user - [23971308]
    When Logged in user requests to create a discussion DISFOO
    Then Discussion DISFOO should be created successfully
    And User BZU logs in
    Then Logged in user Like discussion DISFOO

    # Auto generated by chrome-extension on Tue, 02 Apr 2019 16:23:38 GMT
  Scenario: API - Verify that user A receives notification "Latest Acclaim ; Positive feedback on your contributions" when User B likes discussion of User A - [23971327]
    Given Logged in user requests to create a discussion DISFOO
    Then Discussion DISFOO should be created successfully
    When User request all unread messages for Discussion
    Then Notification of Discussion DISFOO is present in inbox

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 09:06:33 GMT
  Scenario: API - User unlikes Discussion created by another user - [23971309]
    Given Logged in user requests to create a discussion DISFOO
    Then Discussion DISFOO should be created successfully
    When User BZU logs in
    And Logged in user Like discussion DISFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on discussion DISFOO

    # Auto generated by chrome-extension on Tue, 02 Apr 2019 16:23:39 GMT
  Scenario: API - Verify the message received in inbox "Latest Acclaim ; Positive feedback on your contributions" is removed when User B unlikes discussion of User A - [23971339]
    Given Logged in user requests to create a discussion DISFOO
    Then Discussion DISFOO should be created successfully
    When User request all unread messages for Discussion
    Then Notification of Discussion DISFOO is present in inbox

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 09:11:27 GMT
  Scenario: API - User likes Document created by another user - [23971310]
    Given User request to create a document DOCFOO
    Then Document DOCFOO is created successfully
    When User BZU logs in
    Then Logged in user Like document DOCFOO

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 09:11:27 GMT
  Scenario: API - User unlikes Document created by another user - [23971311]
    Given User request to create a document DOCFOO
    Then Document DOCFOO is created successfully
    When User BZU logs in
    Then Logged in user Like document DOCFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on document DOCFOO

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 13:16:08 GMT
  Scenario: API - User likes Poll created by another user - [23971312]
    When Request to create a Poll POLLFOO
    Then Poll POLLFOO is created successfully
    When User BZU logs in
    Then Logged in user Like poll POLLFOO

     # Auto generated by chrome-extension on Tue, 02 Apr 2019 18:51:22 GMT
  Scenario: API - Verify that user A receives notification "Latest Acclaim ; Positive feedback on your contributions" when User B likes Poll of User A - [23971340]
    Given Request to create a Poll POLLFOO
    Then Poll POLLFOO is created successfully
    When User request all unread messages for Poll
    Then Notification of Poll POLLFOO is present in inbox

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 13:16:08 GMT
  Scenario: API - User unlikes Poll created by another user - [23971313]
    Given ADMIN logged into the system
    And Request to create a Poll POLLFOO
    Then Poll POLLFOO is created successfully
    When User BZU logs in
    And Logged in user Like poll POLLFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on poll POLLFOO

    # Auto generated by chrome-extension on Tue, 02 Apr 2019 18:51:22 GMT
  Scenario: API - Verify the message received in inbox "Latest Acclaim ; Positive feedback on your contributions" is removed when User B unlikes Poll of User A - [23971341]
    Given Request to create a Poll POLLFOO
    Then Poll POLLFOO is created successfully
    When User request all unread messages for Poll
    Then Notification of Poll POLLFOO is present in inbox

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 13:32:36 GMT
  Scenario: API - User like Event created by another user - [23971316]
    Given Logged in user requests to create event EVEFOO with tags TAG
    Then Event EVEFOO is created successfully
    When User BZU logs in
    Then Logged in user Like event EVEFOO

    # Auto generated by chrome-extension on Tue, 02 Apr 2019 19:04:45 GMT
  Scenario: API - Verify that user A receives notification "Latest Acclaim ; Positive feedback on your contributions" when User B likes event of User A - [23971344]
    Given Logged in user requests to create event EVEFOO with tags TAG
    Then Event EVEFOO is created successfully
    When User request all unread messages for Event
    Then Notification of Event EVEFOO is present in inbox

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 13:32:36 GMT
  Scenario: API - User unlikes Event created by another user - [23971317]
    Given Logged in user requests to create event EVEFOO with tags TAG
    Then Event EVEFOO is created successfully
    When User BZU logs in
    And Logged in user Like event EVEFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on event EVEFOO

    # Auto generated by chrome-extension on Tue, 02 Apr 2019 19:04:46 GMT
  Scenario: API - Verify the message received in inbox "Latest Acclaim ; Positive feedback on your contributions" is removed when User B unlikes event of User A - [23971345]
    Given Logged in user requests to create event EVEFOO with tags TAG
    Then Event EVEFOO is created successfully
    When User request all unread messages for Event
    Then Notification of Event EVEFOO is present in inbox

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 13:41:11 GMT
  Scenario: API - User like Question created by another user - [23971320]
    Given Logged in user requests to create Question QUEFOO
    Then Question QUEFOO is created successfully
    When User BZU logs in
    Then Logged in user Like question QUEFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 13:09:07 GMT
  Scenario: API - Verify that user A receives notification "Latest Acclaim ; Positive feedback on your contributions" when User B likes Question of User A - [23971349]
    Given Logged in user requests to create Question QUEFOO
    Then Question QUEFOO is created successfully
    When User request all unread messages for Question
    Then Notification of Question QUEFOO is present in inbox

    # Auto generated by chrome-extension on Sat, 30 Mar 2019 13:41:11 GMT
  Scenario: API - User unlikes Question created by another user - [23971321]
    Given Logged in user requests to create Question QUEFOO
    Then Question QUEFOO is created successfully
    When User BZU logs in
    And Logged in user Like question QUEFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on question QUEFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 13:09:06 GMT
  Scenario: API - Verify the message received in inbox "Latest Acclaim ; Positive feedback on your contributions" is removed when User B unlikes Question of User A - [23971350]
    Given Logged in user requests to create Question QUEFOO
    Then Question QUEFOO is created successfully
    When User request all unread messages for Question
    Then Notification of Question QUEFOO is present in inbox

    # Auto generated by chrome-extension on Mon, 01 Apr 2019 18:10:35 GMT
  Scenario: API - User like File created by another user - [23971318]
    When Logged in user requests to create a File FILEFOO with tags #E2ETag01 And File Path src/test/resources/TestFiles/testPDF.pdf
    Then File FILEFOO is created successfully
    When User BZU logs in
    Then Logged in user Like file FILEFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 09:05:09 GMT
  Scenario: API - Verify that user A receives notification "Latest Acclaim ; Positive feedback on your contributions" when User B likes File of User A - [23971346]
    When Logged in user requests to create a File FILEFOO with tags #E2ETag01 And File Path src/test/resources/TestFiles/testPDF.pdf
    Then File FILEFOO is created successfully
    When User request all unread messages for File
    Then Notification of File FILEFOO is present in inbox

    # Auto generated by chrome-extension on Mon, 01 Apr 2019 18:10:35 GMT
  Scenario: API - User unlikes File created by another user - [23971319]
    When Logged in user requests to create a File FILEFOO with tags #E2ETag01 And File Path src/test/resources/TestFiles/testPDF.pdf
    Then File FILEFOO is created successfully
    When User BZU logs in
    And Logged in user Like file FILEFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on file FILEFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 09:05:10 GMT
  Scenario: API - Verify the message received in inbox "Latest Acclaim ; Positive feedback on your contributions" is removed when User B unlikes File of User A - [23971348]
    When Logged in user requests to create a File FILEFOO with tags #E2ETag01 And File Path src/test/resources/TestFiles/testPDF.pdf
    Then File FILEFOO is created successfully
    When User request all unread messages for File
    Then Notification of File FILEFOO is present in inbox

    # Auto generated by chrome-extension on Mon, 01 Apr 2019 18:10:37 GMT
  @CREATE-VIDEO
  Scenario: API - User like Video created by another user - [23971314]
    Given Request to create video VIDEOFOO
    Then File VIDEOFOO is created successfully
    And User BZU logs in
    And Logged in user Like file VIDEOFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 13:16:35 GMT
  @CREATE-VIDEO
  Scenario: API - Verify that user A receives notification "Latest Acclaim ; Positive feedback on your contributions" when User B likes Video of User A - [23971342]
    Given Request to create video VIDEOFOO
    Then File VIDEOFOO is created successfully
    When User request all unread messages for File
    Then Notification of File VIDEOFOO is present in inbox

    # Auto generated by chrome-extension on Mon, 01 Apr 2019 18:10:37 GMT
  @CREATE-VIDEO
  Scenario: API - User unlikes Video created by another user - [23971315]
    Given Request to create video VIDEOFOO
    Then File VIDEOFOO is created successfully
    When User BZU logs in
    And Logged in user Like file VIDEOFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on file VIDEOFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 13:16:44 GMT
  @CREATE-VIDEO
  Scenario: API - Verify the message received in inbox "Latest Acclaim ; Positive feedback on your contributions" is removed when User B unlikes Video of User A - [23971343]
    Given Request to create video VIDEOFOO
    Then File VIDEOFOO is created successfully
    When User request all unread messages for File
    Then Notification of File VIDEOFOO is present in inbox

    # Auto generated by chrome-extension on Wed, 03 Apr 2019 08:53:22 GMT
  Scenario: API - User like Blog Post created by another user - [23971322]
    Given Logged in user requests to create post POSTFOO with tags TAG
    Then Post POSTFOO is created successfully
    When User BZU logs in
    Then Logged in user Like blog POSTFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 13:13:49 GMT
  Scenario: API - Verify that user A receives notification "Latest Acclaim ; Positive feedback on your contributions" when User B likes Blog Post of User A - [23971351]
    Given Logged in user requests to create post POSTFOO with tags TAG
    Then Post POSTFOO is created successfully
    When User request all unread messages for blog
    Then Notification of blog POSTFOO is present in inbox

    # Auto generated by chrome-extension on Wed, 03 Apr 2019 08:53:22 GMT
  Scenario: API - User unlikes Blog Post created by another user - [23971323]
    Given Logged in user requests to create post POSTFOO with tags TAG
    Then Post POSTFOO is created successfully
    When User BZU logs in
    And Logged in user Like blog POSTFOO
    And User awaits for 5 seconds
    Then Logged in user remove Like added on blog POSTFOO

    # Auto generated by chrome-extension on Thu, 04 Apr 2019 13:13:48 GMT
  Scenario: API - Verify the message received in inbox "Latest Acclaim ; Positive feedback on your contributions" is removed when User B unlikes Blog Post of User A - [23971352]
    Given Logged in user requests to create post POSTFOO with tags TAG
    Then Post POSTFOO is created successfully
    When User request all unread messages for blog
    Then Notification of blog POSTFOO is present in inbox