@APISuite
Feature: [CLOUD API Experimental Suite] - [JVCLD-20509] - [E2E test scenario for JVCLD-14555]

  Background:
    Given We are running E2E JVCLD-20509
    And ADMIN logged into the system
    When User USERONE has been created
    When User USERTWO has been created
    When User USERTHREE has been created
    And  User USERONE logs in

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:35 GMT
  Scenario: API - As a standard "user 1" create a Question in Space and Add Comments - [23971286]
    When User requests to create a space SPACEFOO
    Then Logged in user requests to create question QUESTIONSPACE with tags SPACEFOO
    And Question QUESTIONSPACE is created successfully
    When Add a comment COMMENTFOO to question QUESTIONSPACE
    Then Comment has been added to the question successfully

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:35 GMT
  Scenario: API - As a standard "user 1" create a Question in Group and Add Comments - [23971287]
    When User requests to create a private group GROUPFOO
    Then Logged in user requests to create question QUESTIONGROUP with tags GROUPFOO
    And Question QUESTIONGROUP is created successfully
    When Add a comment COMMENTFOO to question QUESTIONGROUP
    Then Comment has been added to the question successfully

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:37 GMT
  Scenario: API - As a standard "user 1" create a Question in Project and Add Comments - [23971288]
    When User requests to create a project PROJECTFOO under place GROUPFOO
    Then Logged in user requests to create question QUESTIONPROJECT with tags PROJECTFOO
    And Question QUESTIONPROJECT is created successfully
    When Add a comment COMMENTFOO to question QUESTIONPROJECT
    Then Comment has been added to the question successfully

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:38 GMT
  Scenario: API - Verify "user 2", "user 3" can like "Question and its Comments" created in Space - [23971289]
    Then  User USERTWO logs in
    And Logged in user Like question QUESTIONSPACE
    And  User USERTHREE logs in
    And Logged in user Like question QUESTIONSPACE

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:39 GMT
  Scenario: API - Verify "user 2", "user 3" can like "Question and its Comments" created in Group - [23971290]
    Then  User USERTWO logs in
    And Logged in user Like question QUESTIONGROUP
    And  User USERTHREE logs in
    And Logged in user Like question QUESTIONGROUP

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:40 GMT
  Scenario: API - Verify "user 2", "user 3" can like "Question and its Comments" created in Project - [23971291]
    Then  User USERTWO logs in
    And Logged in user Like question QUESTIONPROJECT
    And  User USERTHREE logs in
    And Logged in user Like question QUESTIONPROJECT

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:41 GMT
  Scenario: API - Verify correctness of Total count of Question"s Likes in content tab for Space. - [23971292]
    And ADMIN logged into the system
    Then Verify Question QUESTIONSPACE Like Count Equals 2

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:42 GMT
  Scenario: API - Verify correctness of total count of Question"s Likes in content tab for Group - [23971293]
    And ADMIN logged into the system
    Then Verify Question QUESTIONGROUP Like Count Equals 2

# Auto generated by chrome-extension on Thu, 11 Apr 2019 08:00:42 GMT
  Scenario: API - Verify correctness of total count of Question Likes in content tab for Project - [23971294]
    And ADMIN logged into the system
    Then Verify Question QUESTIONPROJECT Like Count Equals 2