@APISuite
Feature: [CLOUD API Experimental Suite] - [JVCLD-20541]

  Background:
    Given We are running E2E JVCLD-20541
    Given ADMIN logged into the system

    # Auto generated by chrome-extension on Wed, 13 Mar 2019 14:01:13 GMT
  Scenario: API - Create a poll with iframe embedded in a group - [23203781]
    When Request to create an Poll Under Place With Description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe>
    Then Poll is Created Successfully Under Place

    # Auto generated by chrome-extension on Wed, 13 Mar 2019 14:18:13 GMT
  Scenario: API - Create a Poll with iframe embedded - [23203870]
    When Request to create an Poll With Description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe>
    Then Poll is Created Successfully

    # Auto generated by chrome-extension on Wed, 13 Mar 2019 14:18:13 GMT
  Scenario: API - Create a Files with iframe embedded in a group - [23203885]
    When Logged in user requests to create a File FILEFOO with File Path src/test/resources/TestFiles/testPDF.pdf And Description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> under place
    Then File FILEFOO is created successfully

    # Auto generated by chrome-extension on Wed, 13 Mar 2019 14:58:28 GMT
  Scenario: API - Create a File with iframe embedded - [23203888]
    When Logged in user requests to create a File FILEFOOO with File Path src/test/resources/TestFiles/testPDF.pdf And Description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> in community
    Then File FILEFOOO is created successfully

    # Auto generated by chrome-extension on Wed, 13 Mar 2019 16:36:54 GMT
  Scenario: API - Create an event with iframe embedded in a group - [23203777]
    When Logged in user requests to create open event EVENTFOO with description "<p>Test iframe </p><iframe src='https://www.wrike.com' width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe>" in group
    Then Event EVENTFOO is created successfully

    # Auto generated by chrome-extension on Wed, 13 Mar 2019 16:36:54 GMT
  Scenario: API - Create an event with iframe embedded - [23203779]
    When Logged in user requests to create open event EVENTFOO with description "<p>Test iframe </p><iframe src='https://www.wrike.com' width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe>" in community
    Then Event EVENTFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 09:55:02 GMT
  Scenario: API - Create a blog post with iframe embedded in a group - [23205267]
    When Logged in user requests to create BlogPost POSTFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> under place
    Then Post POSTFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 09:55:06 GMT
  Scenario: API - Create a blog post with iframe embedded - [23205268]
    When Logged in user requests to create BlogPost POSTFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> in community
    Then Post POSTFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 10:28:10 GMT
  Scenario: API - Create a discussion with iframe embedded in a group - [23205271]
    When Logged in user requests to create Discussion DISFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> under place
    Then Discussion DISFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 10:28:10 GMT
  Scenario: API - Create a discussion with iframe embedded - [23205273]
    When Logged in user requests to create Discussion DISFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> in community
    Then Discussion DISFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 10:53:34 GMT
  Scenario: API - Create a question with iframe embedded in Group - [23205274]
    When Logged in user requests to create Question QUESFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> under place
    Then Question QUESFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 10:53:33 GMT
  Scenario: API - Create a question with iframe embedded - [23205276]
    When Logged in user requests to create Question QUESFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> in community
    Then Question QUESFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 11:23:05 GMT
  Scenario: API - Create a document with iframe embedded in a group - [23205277]
    When Logged in user requests to create Document DOCFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> under place
    Then Document DOCFOO is created successfully

    # Auto generated by chrome-extension on Thu, 21 Mar 2019 11:23:06 GMT
  Scenario: API - Create a document with iframe embedded - [23205278]
    When Logged in user requests to create Document DOCFOO with description <p>Test iframe </p><iframe src="https://www.wrike.com" width='100%' height='880' style='width: 1px; min-width: 100%; max-width:1232px; border: 0px;' scrolling='no'></iframe> in community
    Then Document DOCFOO is created successfully