@APISuite
Feature: [CLOUD API Experimental Suite] - [JVCLD-8760]

  Background:
    Given We are running E2E JVCLD-8760
    Given ADMIN logged into the system

    # Auto generated by chrome-extension on Tue, 12 Mar 2019 08:34:22 GMT
  Scenario: API - Create Document content, add "tag" in RTE - [23201180]
    When Logged in user requests to create document DOCFOO with tags #E2ETag01
    Then Document DOCFOO is created successfully

    # Auto generated by chrome-extension on Tue, 12 Mar 2019 08:34:23 GMT
  Scenario: API- Create Discussion content, add "tag" in RTE - [23201182]
    When Logged in user requests to create a discussion DISFOO with tags #E2ETag01
    Then Discussion DISFOO is created successfully

    # Auto generated by chrome-extension on Tue, 12 Mar 2019 08:34:25 GMT
  Scenario: API - Create Question content, add "tag" in RTE, in the "The Jive Community" place - [23201184]
    When Logged in user requests to create question QUESTIONFOO with tags #E2ETag01
    Then Question QUESTIONFOO is created successfully

    # Auto generated by chrome-extension on Tue, 12 Mar 2019 08:34:25 GMT
  Scenario: API - Create Blog Post content, add "tag" in RTE, in the project - [23201187]
    When Logged in user requests to create post POSTFOO with tags #E2ETag01
    Then Post POSTFOO is created successfully

    # Auto generated by chrome-extension on Tue, 12 Mar 2019 10:33:54 GMT
  Scenario: API - Create Poll content, add "tag" in RTE, in the group - [23201334]
    When Logged in user requests to create a Poll POLLFOO with tags #E2ETag01
    Then Poll POLLFOO is created successfully

    # Auto generated by chrome-extension on Tue, 12 Mar 2019 10:34:07 GMT
  Scenario: API - Create File content, add "tag" in RTE, with the Specific Person - [23201338]
    When Logged in user requests to create a File FILEFOO with tags #E2ETag01 And File Path src/test/resources/TestFiles/testPDF.pdf
    Then File FILEFOO is created successfully

   # Auto generated by chrome-extension on Tue, 12 Mar 2019 14:39:43 GMT
  Scenario: API - Search for the content created based on tags - [23201340]
    When User request to search post POSTFOO by subject from spotlight
    Then Post POSTFOO is searched successfully